# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: cork-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:

  - name: CorkConfig
    address:
    - 0xE5c5C29e32b9ef3eE63c2c22A588d7eB4AAf328e
    handler: src/EventHandlers.ts
    events:
    - event: CorkPoolSet(address corkPool)
    - event: Paused(address account)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: TreasurySet(address treasury)
    - event: Unpaused(address account)

  - name: CorkPool
    address:
    - 0xDF181Defd2A02171A9cDacB24B171DB9cDc9bEd6
    handler: src/EventHandlers.ts
    events:
    - event: BaseRedemptionFeePercentageUpdated(bytes32 indexed id, uint256 indexed baseRedemptionFeePercentage)
    - event: Deposit(bytes32 indexed marketId, address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: DepositPaused(bytes32 indexed marketId)
    - event: DepositUnpaused(bytes32 indexed marketId)
    - event: Initialized(uint64 version)
    - event: MarketCreated(bytes32 indexed id, address indexed referenceAsset, address indexed collateralAsset, uint256 expiry, address exchangeRateProvider, address principalToken, address swapToken)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: ReturnPaused(bytes32 indexed marketId)
    - event: ReturnUnpaused(bytes32 indexed marketId)
    - event: Swap(bytes32 indexed id, address indexed swaper, uint256 paUsed, uint256 swapTokenUsed, uint256 raReceived, uint256 dsExchangeRate, uint256 feePercentage, uint256 fee)
    - event: SwapPaused(bytes32 indexed marketId)
    - event: SwapUnpaused(bytes32 indexed marketId)
    - event: UnwindSwap(bytes32 indexed id, address indexed buyer, uint256 raUsed, uint256 receivedReferenceAsset, uint256 receivedSwapToken, uint256 feePercentage, uint256 fee, uint256 exchangeRates)
    - event: UnwindSwapFeeRateUpdated(bytes32 indexed id, uint256 indexed unwindSwapFeeRate)
    - event: UnwindSwapPaused(bytes32 indexed marketId)
    - event: UnwindSwapUnpaused(bytes32 indexed marketId)
    - event: Upgraded(address indexed implementation)
    - event: WithdrawExtended(bytes32 indexed marketId, address indexed sender, address indexed owner, uint256 assets0, uint256 assets1, uint256 shares0, uint256 shares1)
    - event: WithdrawalPaused(bytes32 indexed marketId)
    - event: WithdrawalUnpaused(bytes32 indexed marketId)

  - name: ExchangeRateProvider
    address:
    - 0x8480B2ea4a367de5b1E0Df4803F1872002f3C6e5
    handler: src/EventHandlers.ts
    events:
    - event: RateUpdated(bytes32 indexed id, uint256 newRate)

  - name: SharesFactory
    address:
    - 0xDCed1d589bbc522d8C6843c39203d40DC2eD0B5b
    handler: src/EventHandlers.ts
    events:
    - event: CorkPoolChanged(address indexed oldCorkPool, address indexed newCorkPool)
    - event: Initialized(uint64 version)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    # - event: SharesDeployed(address indexed collateralAsset, address indexed principalToken, address indexed swapToken) # Same event as MarketCreated in CorkPool
    - event: Upgraded(address indexed implementation)
    
  - name: CPT
    abi_file_path: ./abis/ERC4626.json 
    handler: src/EventHandlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: Deposit(address indexed caller, address indexed owner, uint256 assets, uint256 shares)
      - event: Withdraw(address indexed caller, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
      
  - name: CST
    abi_file_path: ./abis/ERC4626.json 
    handler: src/EventHandlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
unordered_multichain_mode: true
