on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      app_name:    { required: true, type: string }
      image_tag:   { required: true, type: string }
      config_file: { required: false, type: string, default: "config.yaml" }
      vcpu:        { required: false, type: string, default: "2" }
      memory:      { required: false, type: string, default: "2048" }
      disk_size:   { required: false, type: string, default: "10" }
    secrets:
      PHALA_CLOUD_API_KEY:          { required: true }
      DOCKER_IMAGE:                 { required: true }
      DSTACK_AWS_ACCESS_KEY_ID:     { required: true }
      DSTACK_AWS_SECRET_ACCESS_KEY: { required: true }
      DSTACK_AWS_REGION:            { required: true }
      DSTACK_AWS_ECR_REGISTRY:      { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      APP_NAME:    ${{ inputs.app_name }}
      DOCKER_TAG:  ${{ inputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Render docker-compose (YAML-safe)
        id: render
        shell: bash
        env:
          FULL_IMAGE: ${{ secrets.DOCKER_IMAGE }}:${{ inputs.image_tag }}   # ecr repo:tag
          APP_NAME:   ${{ inputs.app_name }}
          DSTACK_AWS_ACCESS_KEY_ID:      ${{ secrets.DSTACK_AWS_ACCESS_KEY_ID }}
          DSTACK_AWS_SECRET_ACCESS_KEY:  ${{ secrets.DSTACK_AWS_SECRET_ACCESS_KEY }}
          DSTACK_AWS_REGION:             ${{ secrets.DSTACK_AWS_REGION }}
          DSTACK_AWS_ECR_REGISTRY:       ${{ secrets.DSTACK_AWS_ECR_REGISTRY }}
        run: |
          set -euo pipefail
          cp docker-compose.yml docker-compose.rendered.yml
      
          # fetch yq (static binary)
          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq
          chmod +x yq
      
          # set the exact image and container_name for the envio-indexer service
          ./yq -i '.services."envio-indexer".image = strenv(FULL_IMAGE)' docker-compose.rendered.yml
          ./yq -i '.services."envio-indexer".container_name = strenv(APP_NAME)' docker-compose.rendered.yml
      
          # inject ECR auth envs so Phala can pull private ECR
          ./yq -i '.services."envio-indexer".environment.DSTACK_AWS_ACCESS_KEY_ID     = strenv(DSTACK_AWS_ACCESS_KEY_ID)' docker-compose.rendered.yml
          ./yq -i '.services."envio-indexer".environment.DSTACK_AWS_SECRET_ACCESS_KEY = strenv(DSTACK_AWS_SECRET_ACCESS_KEY)' docker-compose.rendered.yml
          ./yq -i '.services."envio-indexer".environment.DSTACK_AWS_REGION            = strenv(DSTACK_AWS_REGION)' docker-compose.rendered.yml
          ./yq -i '.services."envio-indexer".environment.DSTACK_AWS_ECR_REGISTRY      = strenv(DSTACK_AWS_ECR_REGISTRY)' docker-compose.rendered.yml
      
          # guard: fail if any placeholders remain
          if grep -E '\$\{(DOCKER_IMAGE|DSTACK_AWS_.*?)' -n docker-compose.rendered.yml; then
            echo "::error::Placeholders still present in rendered compose"; exit 1; fi
      
          echo "compose=docker-compose.rendered.yml" >> "$GITHUB_OUTPUT"
    
      - name: Deploy to Phala Cloud
        uses: Leechael/phala-deploy-action@v2
        with:
          phala-api-key: ${{ secrets.PHALA_CLOUD_API_KEY }}
          cvm-name:      ${{ inputs.app_name }}
          compose-file:  ${{ steps.render.outputs.compose }}
          vcpu:          ${{ inputs.vcpu }}
          memory:        ${{ inputs.memory }}
          disk-size:     ${{ inputs.disk_size }}
        
          envs: |
            DSTACK_AWS_ACCESS_KEY_ID: ${{ secrets.DSTACK_AWS_ACCESS_KEY_ID }}
            DSTACK_AWS_SECRET_ACCESS_KEY: ${{ secrets.DSTACK_AWS_SECRET_ACCESS_KEY }}
            DSTACK_AWS_REGION: ${{ secrets.DSTACK_AWS_REGION }}
            DSTACK_AWS_ECR_REGISTRY: ${{ secrets.DSTACK_AWS_ECR_REGISTRY }}