name: Build, Push & Deploy envio-indexer to Phala Cloud

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'tsconfig.json'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

env:                       
  APP_NAME:                  ${{ vars.APP_NAME           || secrets.APP_NAME }}
  DOCKER_IMAGE:              ${{ vars.DOCKER_IMAGE       || secrets.DOCKER_IMAGE }}   
  DOCKER_REGISTRY:           ${{ vars.DOCKER_REGISTRY || secrets.DOCKER_REGISTRY || 'docker.io' }}
  DOCKER_REGISTRY_USERNAME:  ${{ vars.DOCKER_REGISTRY_USERNAME || secrets.DOCKER_REGISTRY_USERNAME || github.actor }}
  DOCKER_REGISTRY_PASSWORD:  ${{ vars.DOCKER_REGISTRY_PASSWORD || secrets.DOCKER_REGISTRY_PASSWORD }}
  PHALA_CLOUD_API_KEY:       ${{ vars.PHALA_CLOUD_API_KEY || secrets.PHALA_CLOUD_API_KEY }}

jobs:
  test-build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.7.1
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Build & Test
        run: |
          pnpm install --frozen-lockfile
          pnpm codegen && pnpm build

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Update Docker Compose
        run: |
          sed -i "s|\${DOCKER_IMAGE}|${DOCKER_IMAGE}|g" ./docker-compose.yml
      - name: Deploy to Phala Cloud
        uses: Leechael/phala-deploy-action@v2
        with:
          phala-api-key: ${{ secrets.PHALA_CLOUD_API_KEY }}
          cvm-name: ''
          compose-file:     './docker-compose.yml'
          vcpu: '2'                         # Default: '2'
          memory: '2048'                    # Default: '2048'
          disk-size: '10'                   # Default: '40'
          envs: |                           # Environment variables in YAML format (will be converted to dotenv)
            EXAMPLE_ENV_VAR: 'none'
          app-id: ''                        # App ID of existing CVM to (if updating)
          node-id: ''                       # Node ID (Teepod ID)
          base-image: ''                    # Base image to use for the CVM
