name: Build, Push & Deploy envio-indexer to Phala Cloud

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'tsconfig.json'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

env:           
  DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
  DOCKER_REGISTRY: 'docker.io'
  APP_NAME: 'cork-user-balance'

jobs:
  test-build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies, build, and test
        run: |
          pnpm install --frozen-lockfile
          pnpm codegen

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ env.APP_NAME }}-cache
          cache-to: type=gha,scope=${{ env.APP_NAME }}-cache,mode=max

      - name: Update Docker Compose for deployment
        run: |
          sed -i "s|\${DOCKER_IMAGE}|${DOCKER_IMAGE}|g" ./docker-compose.yml

      - name: Deploy to Phala Cloud
        uses: Leechael/phala-deploy-action@v2
        with:
          phala-api-key: ${{ secrets.PHALA_CLOUD_API_KEY }}
          cvm-name: ${{ env.APP_NAME }}
          compose-file:     './docker-compose.yml'
          vcpu: '2'                         
          memory: '2048'                    
          disk-size: '10'            
          app-id: ${{ secrets.PHALA_APP_ID }}
